import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import reducer from './reducers';
import App from './routes/App';

const initialState = {
  'user': {},
  'playing': {},
  'myList': [],
  'trends': [
    {
      'id': 2,
      'slug': 'tvshow-2',
      'title': 'In the Dark',
      'type': 'Scripted',
      'language': 'English',
      'year': 2009,
      'contentRating': '16+',
      'duration': 164,
      'cover': 'https://i.ytimg.com/vi/2vtos1qUnvE/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBea0jwHITIR3gyEVDdGc_R_nPByA',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://www.youtube.com/embed/adLGHcj_fmA',
    },
    {
      'id': 3,
      'slug': 'tvshow-3',
      'title': 'Instinct',
      'type': 'Adventure',
      'language': 'English',
      'year': 2002,
      'contentRating': '16+',
      'duration': 137,
      'cover': 'https://i.ytimg.com/vi/CFPLIaMpGrY/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCHEOVbA9P4Z-fbthfSBL6H-z8NNA',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://www.youtube.com/embed/CFPLIaMpGrY',
    },
    {
      'id': 4,
      'slug': 'tvshow-4',
      'title': 'Grand Hotel',
      'type': 'Comedy',
      'language': 'English',
      'year': 2014,
      'contentRating': '16+',
      'duration': 163,
      'cover': 'https://i.ytimg.com/vi/srP6183TjIM/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCk17CRE2W7zbJaLET0o8jhIbdrnQ',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://www.youtube.com/embed/srP6183TjIM',
    },
    {
      'id': 5,
      'slug': 'tvshow-5',
      'title': 'Stargate Atlantis',
      'type': 'Scripted',
      'language': 'English',
      'year': 2014,
      'contentRating': '16+',
      'duration': 194,
      'cover': 'https://i.ytimg.com/vi/TkNi-FudBKw/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDYQQd5kf7TSGleKo1YFqp2qoHB5Q',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://www.youtube.com/embed/TkNi-FudBKw',
    },
    {
      'id': 6,
      'slug': 'tvshow-6',
      'title': 'Final Space',
      'type': 'Scripted',
      'language': 'English',
      'year': 2017,
      'contentRating': '16+',
      'duration': 124,
      'cover': 'https://i.ytimg.com/vi/orJSJGHjBLI/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCPKfINO-f8RMcs1xdi1JhRd5AGUA',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://www.youtube.com/embed/orJSJGHjBLI?list=PLMC9KNkIncKtGvr2kFRuXBVmBev6cAJ2u',
    },
    {
      'id': 7,
      'slug': 'tvshow-7',
      'title': 'The Kid LAROI, Justin Bieber - STAY',
      'type': 'Drama',
      'language': 'English',
      'year': 2011,
      'contentRating': '16+',
      'duration': 179,
      'cover': 'https://i.ytimg.com/vi/kTJczUoc26U/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCbWD-Ov1kibZCYAcOPM4lVBdboOA',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://www.youtube.com/embed/kTJczUoc26U?list=PLMC9KNkIncKtGvr2kFRuXBVmBev6cAJ2u',
    },
    {
      'id': 66,
      'slug': 'tvshow-6',
      'title': 'Final Space',
      'type': 'Scripted',
      'language': 'English',
      'year': 2017,
      'contentRating': '16+',
      'duration': 124,
      'cover': 'https://i.ytimg.com/vi/orJSJGHjBLI/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCPKfINO-f8RMcs1xdi1JhRd5AGUA',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://www.youtube.com/embed/orJSJGHjBLI?list=PLMC9KNkIncKtGvr2kFRuXBVmBev6cAJ2u',
    },
    {
      'id': 77,
      'slug': 'tvshow-7',
      'title': 'The Kid LAROI, Justin Bieber - STAY',
      'type': 'Drama',
      'language': 'English',
      'year': 2011,
      'contentRating': '16+',
      'duration': 179,
      'cover': 'https://i.ytimg.com/vi/kTJczUoc26U/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCbWD-Ov1kibZCYAcOPM4lVBdboOA',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://www.youtube.com/embed/kTJczUoc26U?list=PLMC9KNkIncKtGvr2kFRuXBVmBev6cAJ2u',
    },
  ],
  'originals': [
    {
      'id': 8,
      'slug': 'tvshow-8',
      'title': 'JAWNY - Tombstone Grey',
      'type': 'Action',
      'language': 'English',
      'year': 2012,
      'contentRating': '16+',
      'duration': 148,
      'cover': 'https://i.ytimg.com/vi/GByVoG_lX6g/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB1KDo1BDwn6AK4Jjb-VW-ZOXWtww',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://www.youtube.com/embed/GByVoG_lX6g?list=PLMC9KNkIncKtGvr2kFRuXBVmBev6cAJ2u',
    },
    {
      'id': 9,
      'slug': 'tvshow-9',
      'title': 'Billie Eilish - Happier Than Ever',
      'type': 'Action',
      'language': 'English',
      'year': 2019,
      'contentRating': '16+',
      'duration': 128,
      'cover': 'https://i.ytimg.com/vi/5GJWxDKyk3A/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBKHz09QTikICj_EZKs8mYrojE31A',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://www.youtube.com/embed/5GJWxDKyk3A?list=PLMC9KNkIncKtGvr2kFRuXBVmBev6cAJ2u',
    },
    {
      'id': 10,
      'slug': 'tvshow-10',
      'title': 'Elementary',
      'type': 'Animation',
      'language': 'English',
      'year': 2011,
      'contentRating': '16+',
      'duration': 346,
      'cover': 'https://i.ytimg.com/vi/2ORj3T5sz-0/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBtQRj_vE1_0GGAgp4HtxxqrHWeZQ',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://www.youtube.com/embed/2ORj3T5sz-0?list=PLMC9KNkIncKtGvr2kFRuXBVmBev6cAJ2u',
    },
    {
      'id': 11,
      'slug': 'tvshow-11',
      'title': 'Dua Lipa - Love Again',
      'type': 'War',
      'language': 'English',
      'year': 2015,
      'contentRating': '16+',
      'duration': 226,
      'cover': 'https://i.ytimg.com/vi/BC19kwABFwc/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLANyn9qYG4rhTu0PiWwstRII8PWMg',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://www.youtube.com/embed/BC19kwABFwc?list=PLMC9KNkIncKtGvr2kFRuXBVmBev6cAJ2u',
    },
    {
      'id': 12,
      'slug': 'tvshow-12',
      'title': 'Charlotte Cardin and Lubalin - Phoenix',
      'type': 'Comedy',
      'language': 'English',
      'year': 2018,
      'contentRating': '16+',
      'duration': 190,
      'cover': 'https://i.ytimg.com/vi/sk9Gcl-t8qQ/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBWmvmPb4FyH5nSVRcPDapK_tWoaw',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://www.youtube.com/embed/sk9Gcl-t8qQ?list=PLMC9KNkIncKtGvr2kFRuXBVmBev6cAJ2u',
    },
    {
      'id': 13,
      'slug': 'tvshow-13',
      'title': 'Jax - Like My Father',
      'type': 'Drama',
      'language': 'English',
      'year': 2010,
      'contentRating': '16+',
      'duration': 160,
      'cover': 'https://i.ytimg.com/vi/GCWl50HQZIM/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBC6iyblHuUxmz9AO-fVGk1Ce-NMg',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://www.youtube.com/embed/GCWl50HQZIM?list=PLMC9KNkIncKtGvr2kFRuXBVmBev6cAJ2u',
    },
    {
      'id': 122,
      'slug': 'tvshow-12',
      'title': 'Charlotte Cardin and Lubalin - Phoenix',
      'type': 'Comedy',
      'language': 'English',
      'year': 2018,
      'contentRating': '16+',
      'duration': 190,
      'cover': 'https://i.ytimg.com/vi/sk9Gcl-t8qQ/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBWmvmPb4FyH5nSVRcPDapK_tWoaw',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://www.youtube.com/embed/sk9Gcl-t8qQ?list=PLMC9KNkIncKtGvr2kFRuXBVmBev6cAJ2u',
    },
    {
      'id': 133,
      'slug': 'tvshow-13',
      'title': 'Jax - Like My Father',
      'type': 'Drama',
      'language': 'English',
      'year': 2010,
      'contentRating': '16+',
      'duration': 160,
      'cover': 'https://i.ytimg.com/vi/GCWl50HQZIM/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBC6iyblHuUxmz9AO-fVGk1Ce-NMg',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://www.youtube.com/embed/GCWl50HQZIM?list=PLMC9KNkIncKtGvr2kFRuXBVmBev6cAJ2u',
    },
  ],
};

const store = createStore(reducer, initialState);

ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('app'),
);
